import type { components } from './api.generated'

export type Project = components['schemas']['ProjectOut']
export type SiteTrendPoint = components['schemas']['SiteTrendPointOut']
export type SiteTrend = components['schemas']['SiteTrendOut']
export type Session = components['schemas']['SessionOut']
export type SessionSearchSource = SessionSearchMatch['source']
export type SessionSearchMatch = components['schemas']['SessionSearchMatchOut']
export type SessionSearchResult = components['schemas']['SessionSearchOut']
export type BulkSessionOperation = BulkSessionResponse['operation']
export type BulkSessionOutcome = components['schemas']['BulkSessionOutcome']
export type BulkSessionResponse = components['schemas']['BulkSessionResponse']
export type Image = components['schemas']['ImageOut']
export type Footprint = components['schemas']['FootprintOut']
export type CoverageResult = components['schemas']['CoverageRunOut']
export type TrainingMetricPoint = components['schemas']['TrainingMetricPoint']
export type CoverageGapCell = components['schemas']['CoverageGapCell']
export type EffectiveSplatSettings = components['schemas']['EffectiveSplatSettings']
export type Reconstruction = components['schemas']['ReconstructionContract']
export type MeshStatus = components['schemas']['MeshStatusOut']
export type FlythroughStatus = components['schemas']['FlythroughStatusOut']
export type SemanticClassName = keyof SemanticSummary['class_counts']
export type SemanticStatus = components['schemas']['SemanticStatusOut']
export type SemanticSummary = components['schemas']['SemanticSummary']
export type HistogramBin = components['schemas']['HistogramBin']
export type PreflightQualityReport = components['schemas']['PreflightReportContract']
export type QuickReport = components['schemas']['QuickReportOut']
export type Job = components['schemas']['Job']
export type StorageSessionBreakdown = components['schemas']['StorageSessionBreakdown']
export type StorageStats = components['schemas']['StorageStats']
export type BackupScheduleStatus = components['schemas']['BackupScheduleStatus']
export type SystemAccelerator = components['schemas']['SystemAccelerator']
export type SystemResources = components['schemas']['SystemResources']
export type SystemTool = components['schemas']['SystemTool']
export type WorkflowStatus = components['schemas']['WorkflowStatus']
export type OrthoStatus = components['schemas']['OrthoStatus']
export type GeoTransform = components['schemas']['GeoTransform']
export type StorageFileItem = components['schemas']['StorageFileItem']
export type StorageFileList = components['schemas']['StorageFileList']
export type PolicyCandidate = components['schemas']['PolicyCandidate']
export type PolicySummary = components['schemas']['PolicySummary']
export type PolicyResult = components['schemas']['PolicyResult']
export type SurveyReport = components['schemas']['SurveyReport']
export type Annotation = components['schemas']['AnnotationOut']
export type FlightEntry = components['schemas']['FlightEntryOut']
export type DefectCategory = components['schemas']['DefectIn']['category']
export type DefectSeverity = NonNullable<components['schemas']['DefectIn']['severity']>
export type DefectImageRef = components['schemas']['DefectImageOut']
export type Defect = components['schemas']['DefectOut']
export type SessionComparison = components['schemas']['ComparisonOut']
export type ComparisonCell = components['schemas']['ComparisonCell']
export type ComparisonDiff = components['schemas']['ComparisonDiff']
export type QualityScorecard = components['schemas']['QualityScorecard']
export type GcpResidual = components['schemas']['GcpResidual']
export type GcpAccuracyPoint = components['schemas']['SurveyedGcpIn']
export type GcpAccuracyReport = components['schemas']['GcpAccuracyReport']
export type CheckpointResult = components['schemas']['CheckpointResult']
export type CheckpointValidationReport = components['schemas']['CheckpointValidationReport']

export const SEMANTIC_CLASS_COLORS: Record<SemanticClassName, string> = {
  ground: '#8a7a5c',
  vegetation: '#4F6349',
  structure: '#9A5E32',
  vehicle: '#3b82f6',
  water: '#38bdf8',
  other: '#9ca3af',
}

export type CreatedShareLink = components['schemas']['CreatedShareLink']
export type ShareLinkState = components['schemas']['ShareLinkState']
export type AppSettings = components['schemas']['AppSettings']
export type SessionProgress = components['schemas']['SessionProgress']
export type ShareViewerPayload = components['schemas']['ShareViewerPayload']
export type TargetAreaOut = components['schemas']['TargetAreaOut']
export type PlanOut = components['schemas']['PlanOut']
export type ValidationOut = components['schemas']['ValidationOut']
export type SegmentOut = components['schemas']['SegmentOut']
export type StartUploadResponse = components['schemas']['StartUploadResponse']
export type CompleteUploadResponse = components['schemas']['CompleteUploadContract']
export type LogEntryOut = components['schemas']['LogEntryOut']
